language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - git clone https://github.com/Microsoft/vcpkg.git
  - ./vcpkg/bootstrap-vcpkg
  - cmake -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo
  - cmake --build build --config RelWithDebInfo