name: Build Shuffle

on:
  push:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    permissions: write-all
    runs-on: ${{ matrix.config.os }}-latest
    strategy:
      matrix:
        config:
          - os: ubuntu
            configure: ./vcpkg/bootstrap-vcpkg.sh
          - os: macos
            configure: ./vcpkg/bootstrap-vcpkg.sh
          - os: windows
            configure: .\vcpkg\bootstrap-vcpkg.bat

    steps:
      - uses: actions/checkout@v3

      - name: Update Submodule
        run: "git submodule update --init --recursive"

      - name: Download vcpkg
        run: git clone https://github.com/Microsoft/vcpkg.git
      - name: Configure vcpkg
        run: ${{ matrix.config.configure }}

      - name: Install Packages
        run: "./vcpkg/vcpkg install"

      - name: Configure CMake
        run: cmake -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake -S ${{github.workspace}} -B ${{github.workspace}}/build-${{ matrix.config.os }} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - run: cmake --build ${{github.workspace}}/build-${{ matrix.config.os }} --config ${{env.BUILD_TYPE}}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.config.os }}
          path: |
            build-${{ matrix.config.os }}/src
            !build-${{ matrix.config.os }}/CMakeFiles
            !build-${{ matrix.config.os }}/cmake_install.cmake
            !build-${{ matrix.config.os }}/Makefile
            !build-${{ matrix.config.os }}/*.cbp
  release:
    permissions: write-all
    needs: [ build ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - os: ubuntu
          - os: macos
          - os: windows

    steps:
      - uses: actions/checkout@v3

      - name: Update Submodule
        run: "git submodule update --init --recursive"

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{secrets.MAIL_CONNECTION}}
          server_address: smtp.gmail.com
          server_port: 587
          secure: true
          subject: Github Actions job result
          to: sihu@syuk.me
          from: Shuffle
          attachments: build/*