name: Build Shuffle

on:
  push:
    branches: ["main"]

env:
  BUILD_TYPE: Release

jobs:
  build:
    permissions: write-all
    runs-on: ${{ matrix.config.os }}-latest
    strategy:
      matrix:
        config:
        - os: ubuntu
          configure: ./vcpkg/bootstrap-vcpkg.sh
        - os: macos
          configure: ./vcpkg/bootstrap-vcpkg.sh
        - os: windows
          configure: .\vcpkg\bootstrap-vcpkg.bat

    steps:
    - uses: actions/checkout@v3
    
    - name: Update Submodule
      run: "git submodule update --init --recursive"
        
    - name: Download vcpkg
      run: git clone https://github.com/Microsoft/vcpkg.git
    - name: Configure vcpkg
      run: ${{ matrix.config.configure }}
      
    - name: Install Packages
      run: "./vcpkg/vcpkg install"

    - name: Configure CMake
      run: cmake -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
